# Generated by Django 4.1.7 on 2023-03-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbsnote', '0002_board_update_date_alter_board_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
